"use client";

import { useAppStore } from "@/store/app-store";
import { Language } from "@/types";

const koTextMap: Record<string, string> = {
  // Common UI
  "Home": "홈",
  "Pass": "패스",
  "Explore": "탐색",
  "Assistant": "회화",
  "More": "더보기",
  "My": "내 정보",
  "SOS": "긴급 도움",
  "Calendar": "캘린더",
  "Stamps": "스탬프",
  "Promotions": "프로모션",
  "Back": "뒤로",
  "Close": "닫기",
  "Open": "열기",
  "Save": "저장",
  "Saved": "저장",
  "Copy": "복사",
  "Copied!": "복사됨!",
  "Show": "보여주기",
  "Open Calendar": "캘린더 열기",
  "Open Pass": "패스 열기",
  "Open Stay": "스테이 열기",
  "View all": "전체 보기",
  "View details": "상세 보기",
  "Open details": "상세 보기",
  "Map": "지도",
  "Google Maps": "구글 지도",
  "NAVER Map": "네이버 지도",

  // Shared statuses / labels
  "Recommended": "추천",
  "Selected": "선택됨",
  "Completed": "완료",
  "Mark complete": "완료로 표시",
  "Remove": "삭제",
  "Open related page": "관련 페이지 열기",
  "Open official resource": "공식 자료 열기",
  "Open official booking / event page": "공식 예약 / 이벤트 페이지 열기",
  "Open in Google Maps": "구글 지도에서 열기",
  "Open in NAVER Map app": "네이버 지도 앱에서 열기",
  "Choose which map app should open this route.": "이 경로를 열 지도를 선택하세요.",
  "Great for browser directions and sharing.": "브라우저 길찾기와 공유에 편리합니다.",
  "Helpful when you want a Korea-first navigation app.": "한국에서 많이 쓰는 지도 앱으로 열고 싶을 때 편리합니다.",

  // Top-level loading / shell
  "Loading Landly…": "Landly를 불러오는 중…",
  "Preparing your saved travel setup.": "저장된 이동 설정을 준비하고 있어요.",
  "Loading Landly Pass…": "Landly Pass를 불러오는 중…",
  "Restoring your saved arrival setup.": "저장된 도착 설정을 복원하고 있어요.",
  "Loading Landly Stay…": "Landly Stay를 불러오는 중…",
  "Restoring your saved settlement plan and documents.": "저장된 정착 계획과 문서를 복원하고 있어요.",
  "Preparing your achievement dashboard…": "스탬프 대시보드를 준비하고 있어요…",
  "Preparing events and bookings…": "이벤트와 예약 정보를 준비하고 있어요…",

  // Home
  "Hello, {name}!": "안녕하세요, {name}님!",
  "Travel Mode": "여행 모드",
  "Life Mode": "생활 모드",
  "Switch to Life": "생활 모드로 전환",
  "Switch to Travel": "여행 모드로 전환",
  "South Korea": "대한민국",
  "Open a service": "서비스 바로가기",
  "Thumb-friendly shortcuts to the main Landly flows.": "엄지로 누르기 쉬운 Landly 핵심 기능 바로가기예요.",
  "Today": "오늘",
  "Weather": "날씨",
  "No saved plans yet. Tap to add or view events.": "저장된 일정이 아직 없어요. 눌러서 일정을 추가하거나 확인해보세요.",
  "Arrival 72h": "도착 72시간",
  "Fast-start checklist after landing.": "도착 직후 바로 따라갈 수 있는 체크리스트예요.",
  "Stay 90d": "정착 90일",
  "Long-stay missions with less guesswork.": "장기체류 초반 미션을 더 쉽게 정리해드려요.",
  "Reminders": "리마인더",
  "items need attention.": "건을 확인해야 해요.",
  "Cold and dry": "춥고 건조해요",
  "Warm with humidity": "덥고 습해요",
  "Comfortable seaside weather": "해안가라 비교적 쾌적해요",
  "Mild with breeze": "바람이 있어 비교적 온화해요",
  "Comfortable city weather": "생활하기 무난한 날씨예요",
  "Landly Pass": "패스",
  "Landly Shop": "쇼핑",
  "Landly Care": "케어",
  "Landly Stay": "스테이",
  "Landly SOS": "긴급 도움",
  "Travel smarter from the moment you land.": "도착하는 순간부터 더 똑똑하게 이동하세요.",
  "Compare airport rail, bus, taxi, and the pass that actually fits your Korea trip. Then use the first-72-hours flow so the next step stays obvious.": "공항철도, 리무진버스, 택시, 교통패스를 비교하고 내 일정에 맞는 선택을 하세요. 그리고 도착 72시간 플로우로 다음 행동을 더 명확하게 이어가세요.",
  "Airport routes": "공항 이동",
  "Trusted links": "신뢰 링크",
  "First 72h": "도착 72시간",
  "Companions": "동반자",
  "Shop smarter, refund easier.": "더 똑똑하게 쇼핑하고, 환급은 더 쉽게.",
  "Find foreigner-friendly stores, keep receipts together, and stay ready for departure refund steps.": "외국인이 이용하기 쉬운 매장을 찾고, 영수증을 모아두고, 출국 전 환급 절차를 준비하세요.",
  "Receipt locker": "영수증 보관함",
  "Beauty picks": "뷰티 추천",
  "Check refund": "환급 확인",
  "Get the right help, faster.": "필요한 도움을 더 빨리 찾으세요.",
  "Triage the moment, find foreigner-friendly care, and keep your visit prep ready before you go.": "증상 우선순위를 빠르게 판단하고, 외국인 친화 의료기관을 찾고, 방문 준비를 미리 챙기세요.",
  "Symptom guide": "증상 가이드",
  "Clinic finder": "의료기관 찾기",
  "Open help": "도움 열기",
  "One fast path for emergency phrases, urgent phone numbers, lost-item help, and late-night care decisions.": "긴급 회화, 긴급 전화번호, 분실 대응, 야간 의료 판단을 한 번에 빠르게 이어줍니다.",
  "Quick support": "빠른 도움",
  "Emergency phrase": "긴급 회화",
  "Build your Korea setup plan, track the first 90 days, keep documents close, and jump into official support without guessing where to start.": "한국 정착 계획을 세우고, 첫 90일 미션을 관리하고, 문서를 모아두고, 공식 지원으로 바로 이동하세요.",

  // Pass page / components
  "Overview": "개요",
  "Arrival plan": "도착 계획",
  "Launchers": "바로가기",
  "Phrases": "회화",
  "Saved to Pass and Calendar.": "패스와 캘린더에 저장했어요.",
  "Route saved to Calendar.": "경로를 캘린더에 저장했어요.",
  "Best arrival routes": "추천 도착 경로",
  "Choose the route you actually want, then save that exact option.": "원하는 경로를 직접 고른 뒤 그 경로 그대로 저장하세요.",
  "Save plan": "계획 저장",
  "Open route": "경로 열기",
  "Open taxi": "택시 열기",
  "Best pass for this arrival": "이 도착 조건에 맞는 추천 패스",
  "Why this fits": "추천 이유",
  "Things to watch": "체크할 점",
  "Open the right service fast, or save your own route into Calendar.": "필요한 서비스를 바로 열거나, 직접 만든 경로를 캘린더에 저장하세요.",
  "Quick launch": "빠른 실행",
  "Travel phrase pack": "여행 회화 팩",
  "Keep airport, station, taxi, and last-mile phrases ready before you leave the airport.": "공항, 역, 택시, 마지막 이동 구간에서 필요한 회화를 미리 준비하세요.",
  "No saved pass plans yet": "저장한 패스 계획이 아직 없어요",
  "Save one airport route or pass recommendation so you can pull it up quickly later.": "공항 이동 경로나 패스 추천을 저장해두면 나중에 빠르게 다시 열 수 있어요.",
  "Saved pass plans": "저장한 패스 계획",
  "Re-open the route you planned before landing.": "도착 전에 정해둔 경로를 다시 열어보세요.",
  "Re-open your exact saved route and transport pass decisions.": "저장해둔 경로와 교통 패스 선택을 다시 확인하세요.",
  "Saved route:": "저장한 경로:",
  "Arrival setup": "도착 설정",
  "Choose your airport and destination area. If your destination is not listed, type it directly.": "공항과 도착 지역을 선택하세요. 목록에 없다면 직접 입력해도 됩니다.",
  "Airport": "공항",
  "Arrival date": "도착일",
  "Airport → destination pair": "공항 → 목적지 조합",
  "Quick shortcuts": "빠른 선택",
  "Destination area": "목적지 지역",
  "Type your hotel area or destination": "호텔 지역 또는 목적지를 입력하세요",
  "Arrival time": "도착 시간대",
  "Morning": "오전",
  "Afternoon": "오후",
  "Evening": "저녁",
  "Late night": "심야",
  "Group size": "인원수",
  "Carrying luggage": "짐이 있어요",
  "Late-night arrival": "심야 도착이에요",
  "Plan route to save": "저장할 경로 만들기",
  "Save a route with your date, origin, and destination so you can reopen it from Calendar later.": "날짜, 출발지, 도착지를 입력해 경로를 저장해두면 나중에 캘린더에서 다시 열 수 있어요.",
  "Date": "날짜",
  "Origin": "출발지",
  "Destination": "도착지",
  "Transport": "교통",
  "Choose map app": "지도 앱 선택",
  "Save to Calendar": "캘린더에 저장",
  "Transit / rail": "대중교통 / 철도",
  "Transit / bus": "대중교통 / 버스",
  "Taxi / driving": "택시 / 차량",
  "First 72 hours": "도착 후 72시간",
  "Your calm-start checklist after landing in Korea": "한국 도착 후 차분하게 시작할 수 있는 체크리스트",
  "Progress": "진행도",
  "Before landing": "도착 전",
  "Lock in the essentials before airport stress begins.": "공항의 긴장이 시작되기 전에 필수 항목을 먼저 챙기세요.",
  "Arrival day": "도착 당일",
  "Make the route choice fit your real condition outside the terminal.": "터미널 밖 실제 상황에 맞는 이동 경로를 선택하세요.",
  "First night": "첫날 밤",
  "Keep fallback help close when you are tired and least flexible.": "피곤하고 예민한 시간대에 대비용 도움 경로를 가까이 두세요.",
  "Day 2": "2일차",
  "Turn your first impression into a smarter setup.": "첫인상을 더 똑똑한 생활 준비로 이어가세요.",
  "Day 3": "3일차",
  "Move confirmed plans and backups into a calmer routine.": "확정된 계획과 백업 수단을 더 안정적인 루틴으로 정리하세요.",
  "items": "개",
  "Open related flow": "관련 기능 열기",
  "Pro tip": "팁",
  "Save your chosen arrival route first, then move the confirmed plan into Calendar. It is much easier to trust one saved route than to keep comparing four options after baggage claim.": "먼저 선택한 도착 경로를 저장하고, 확정된 계획을 캘린더로 옮기세요. 수하물을 찾은 뒤 여러 경로를 계속 비교하는 것보다, 저장된 한 경로를 믿고 움직이는 편이 훨씬 편합니다.",
  "Group & companions": "그룹 / 동반자",
  "Plan for the people you are actually moving with": "실제로 함께 움직이는 사람 기준으로 계획하세요",
  "Use this when your best airport route changes because of children, luggage, medical needs, or slower walking speed.": "아이, 짐, 의료 지원, 느린 보행 때문에 최적 경로가 달라질 때 사용하세요.",
  "Apply group size": "인원수 적용",
  "Travelers": "동행 인원",
  "Heavy luggage": "큰 짐",
  "Mobility support": "이동 지원",
  "Medical / night": "의료 / 야간",
  "Add a companion": "동반자 추가",
  "Name or label": "이름 또는 구분명",
  "Relation": "관계",
  "Main language": "주 사용 언어",
  "Mobility": "이동 상태",
  "Late-night support": "야간 지원 필요",
  "Medical support": "의료 지원 필요",
  "Notes": "메모",
  "Save companion": "동반자 저장",
  "Saved companion notes": "저장한 동반자 정보",
  "Keep practical travel constraints visible before you pick a route.": "경로를 고르기 전에 실제 제약사항을 한눈에 확인하세요.",
  "Add the people you are travelling with so route choices stay realistic.": "함께 이동하는 사람을 추가하면 더 현실적인 경로 선택이 가능해요.",

  // Explore / place
  "Card OK": "카드 사용 가능",
  "Open late": "늦게까지 운영",
  "Saved place": "저장한 장소",

  // Phrase card
  "Korean phrase copied.": "한국어 문구를 복사했어요.",
  "Phrase removed from saved list.": "저장한 문구에서 삭제했어요.",
  "Phrase saved for quick reuse.": "빠르게 다시 쓰도록 문구를 저장했어요.",
  "Show this to someone": "상대방에게 보여주세요",
  "Tap anywhere to close": "아무 곳이나 탭해 닫기",

  // Care
  "Triage": "증상 체크",
  "Providers": "의료기관",
  "Visit prep": "방문 준비",
  "Help": "도움 필요",
  "How Landly Care helps": "Landly Care가 도와드리는 방식",
  "Use Landly Care to separate urgent situations from everyday clinic needs, find foreigner-friendly providers, prepare the phrases you may need, and keep your visit summary together.": "Landly Care는 응급 상황과 일반 진료 상황을 구분하고, 외국인 친화 의료기관을 찾고, 필요한 회화를 준비하고, 방문 메모를 한곳에 정리할 수 있게 도와줍니다.",
  "This service is a guide and organizer, not a diagnosis tool or medical advice replacement.": "이 서비스는 안내와 정리를 돕는 도구이며, 진단이나 전문 의료 조언을 대신하지 않습니다.",
  "Search clinic, pharmacy, checkup...": "병원, 약국, 검진센터 검색…",
  "Any language": "언어 전체",
  "International": "국제 진료",
  "Reservation": "예약 가능",
  "No care providers found": "조건에 맞는 의료기관이 없어요",
  "Try another category, language, or a shorter search term.": "카테고리나 언어를 바꾸거나 검색어를 더 짧게 입력해보세요.",
  "KAHF signal": "KAHF 안내",
  "Night hours": "야간 운영",
  "general care": "일반 진료",
  "international clinic": "국제 진료",
  "otc medicine": "일반의약품",
  "travel essentials": "여행 필수품",
  "dental pain": "치과 통증",
  "medical tourism": "의료 관광",
  "checkup coordination": "검진 연계",
  "airport support": "공항 지원",
  "urgent care": "긴급 진료",
  "general clinic": "일반 의원",
  "traveler care": "여행자 진료",

  // Shop
  "Stores": "매장",
  "Checker": "환급 확인",
  "Receipts": "영수증",
  "Guide": "가이드",
  "Departure reminder": "출국 전 알림",
  "How Landly Shop helps": "Landly Shop이 도와드리는 방식",
  "Use Landly Shop to understand common tax refund conditions, keep your receipts together, and review departure-day steps before you head to the airport.": "Landly Shop은 일반적인 세금 환급 조건을 이해하고, 영수증을 한곳에 모아두고, 공항으로 가기 전 출국 당일 해야 할 일을 다시 확인할 수 있게 도와줍니다.",
  "Final eligibility and refund approval still depend on official store and airport procedures.": "최종 환급 가능 여부와 승인 결과는 매장 및 공항의 공식 절차에 따라 달라집니다.",
  "Immediate + general": "즉시 + 일반",
  "Foreign card": "외국 카드",
  "Coupon": "쿠폰",
  "Refund support": "환급 지원",
  "Passport needed": "여권 필요",
  "tourist favorite": "관광객 인기",
  "central Seoul": "서울 중심",
  "late shopping": "늦은 쇼핑",
  "duty free": "면세점",
  "department store": "백화점",
  "quick gifts": "빠른 선물",

  // Stay
  "Checklist": "체크리스트",
  "Documents": "문서",
  "Guides": "가이드",
  "Settle in with less guesswork": "막막함을 줄이고 더 편하게 정착하세요",
  "Review this week's setup tasks": "이번 주 해야 할 정착 작업 보기",
  "How Landly Stay helps": "Landly Stay가 도와드리는 방식",
  "Landly Stay turns official immigration, insurance, housing, labor, and student resources into a clearer setup flow. Use it to decide what to do now, what to save, and where to go for official support.": "Landly Stay는 출입국, 보험, 주거, 노동, 학생 지원 정보를 더 이해하기 쉬운 정착 흐름으로 바꿔드립니다. 지금 해야 할 일, 저장해둘 것, 공식 도움을 받을 곳을 더 명확하게 정리할 수 있어요.",
  "Official route": "공식 경로",
  "Trusted guide": "신뢰 가능한 가이드",
  "Direct contact": "직접 연락 가능",
  "Open link": "링크 열기",

  // Reminder center / My
  "Reminder center": "리마인더 센터",
  "Keep documents, saved plans, and deadlines in one review point": "문서, 저장된 계획, 마감일을 한곳에서 확인하세요",
  "Manual reminders live together with document expiry, arrival plans, calendar events, and 30/90-day stay checkpoints.": "직접 만든 리마인더와 문서 만료일, 도착 계획, 캘린더 일정, 체류 30/90일 체크포인트를 함께 볼 수 있어요.",
  "Total": "전체",
  "Due soon": "곧 도래",
  "Overdue": "기한 지남",
  "Done": "완료",
  "Add manual reminder": "직접 리마인더 추가",
  "Visit immigration office": "출입국 사무소 방문",
  "Optional internal link like /stay?tab=documents": "예: /stay?tab=documents 같은 내부 링크",
  "What should you prepare, bring, or double-check?": "무엇을 준비하고, 챙기고, 다시 확인해야 하나요?",
  "Save reminder": "리마인더 저장",
  "Needs attention": "확인이 필요한 항목",
  "Nothing urgent right now.": "지금 바로 급한 항목은 없어요.",
  "No upcoming items yet.": "예정된 항목이 아직 없어요.",
  "Completed reminders will stay here for quick review.": "완료한 리마인더는 빠르게 다시 확인할 수 있도록 여기에 남아 있어요.",
  "Mark reminder incomplete": "리마인더 완료 취소",
  "Mark reminder complete": "리마인더 완료 표시",
  "Remove reminder": "리마인더 삭제",
  "Places": "장소",
  "Shops": "매장",
  "Pending": "대기 중",
  "Care": "케어",
  "Saved shop stores": "저장한 쇼핑 매장",
  "Your current Landly Shop shortlist.": "현재 저장한 Landly Shop 매장 목록입니다.",
  "Open Shop": "쇼핑 열기",
  "No saved shop stores yet.": "저장한 쇼핑 매장이 아직 없어요.",
  "Receipt tracker": "영수증 추적",
  "Keep pending and needs-check receipts visible before departure.": "출국 전 대기 중이거나 확인이 필요한 영수증을 보이게 관리하세요.",
  "Open locker": "보관함 열기",
  "No pending receipts right now.": "현재 대기 중인 영수증이 없어요.",
  "Saved care providers": "저장한 의료기관",
  "Keep nearby clinics and pharmacies ready for quick access.": "가까운 병원과 약국을 빠르게 다시 열 수 있게 저장해두세요.",
  "Open Care": "케어 열기",
  "No saved providers yet.": "저장한 의료기관이 아직 없어요.",
  "Language": "언어",
  "Current city": "현재 도시",
  "App mode": "앱 모드",
  "Switch mode": "모드 전환",

  // More / calendar / stamps / promotions / SOS
  "Travel tools": "여행 도구",
  "Open quick access tools for arrival, shopping, and emergency support.": "도착, 쇼핑, 긴급 상황에 필요한 기능을 빠르게 여세요.",
  "Life setup": "생활 준비",
  "Review long-stay tasks and your saved profile tools.": "장기체류 준비 항목과 저장한 개인 기능을 확인하세요.",
  "Plans & progress": "일정과 진행 상황",
  "Keep dates, goals, and event picks in one thumb-friendly place.": "일정, 목표, 이벤트를 한 손으로 보기 쉽게 모아두세요.",
  "Plans, deadlines, document vault, and guides.": "계획, 마감일, 문서 보관함, 가이드를 한곳에서 관리하세요.",
  "Saved places, phrases, and personal setup.": "저장한 장소, 회화, 개인 설정을 관리하세요.",
  "Saved arrival plans and custom events show up on their actual dates.": "저장한 도착 계획과 직접 만든 일정이 실제 날짜에 표시돼요.",
  "Review saved route plans or add your own event for this date.": "저장한 경로 계획을 확인하거나 이 날짜에 맞는 나만의 일정을 추가하세요.",
  "No events on this day yet.": "이 날짜에는 아직 일정이 없어요.",
  "Add custom event": "직접 일정 추가",
  "Example: Pick up SIM card": "예: 유심 카드 수령",
  "Optional note": "선택 메모",
  "Save on": "다음 날짜에 저장",
  "Track what you have done in Korea": "한국에서 해낸 일들을 기록해보세요",
  "Use official Landly goals for travel and life moments, or add your own personal mission.": "Landly가 제안하는 여행·생활 목표를 따라가거나, 나만의 개인 목표를 추가해보세요.",
  "Points": "포인트",
  "My goals": "내 목표",
  "Progress by category": "카테고리별 진행도",
  "Add my own goal": "내 목표 추가",
  "Good for resident tasks, food buckets, or small location goals that matter to you.": "정착 준비, 음식 버킷리스트, 가보고 싶은 장소처럼 나에게 중요한 목표를 자유롭게 추가할 수 있어요.",
  "Example: Finish ARC photo prep": "예: 외국인등록증 사진 준비 끝내기",
  "Save my stamp goal": "내 스탬프 목표 저장",
  "My goal": "내 목표",
  "Best in": "추천 지역",
  "Events, promos, and upcoming picks": "이벤트와 프로모션, 다가오는 추천",
  "Keep outside requests and Landly-curated events in one place": "외부 요청 이벤트와 Landly 추천 이벤트를 한곳에서 관리하세요",
  "Use this space to register interest, save dates, and keep booking-related actions organized without losing context.": "관심 등록, 일정 저장, 예약 관련 액션을 한 흐름 안에서 정리하세요.",
  "Live": "진행 중",
  "Upcoming": "예정",
  "Reserved": "예약됨",
  "All": "전체",
  "Now": "지금",
  "Live now": "지금 진행 중",
  "Landly pick": "Landly 추천",
  "Partner / external": "제휴 / 외부",
  "When:": "일정:",
  "Where:": "장소:",
  "City:": "도시:",
  "Interested": "관심 등록됨",
  "Register interest": "관심 등록",
  "In calendar": "캘린더에 있음",
  "Save schedule": "일정 저장",
  "Reserve / book": "예약하기",
  "Fast help when you feel stuck in Korea.": "한국에서 막혔을 때 빠르게 도움을 받으세요.",
  "Keep the right call button close for emergencies, police support, or tourist assistance.": "응급 상황, 경찰 도움, 관광 지원에 맞는 연락 수단을 바로 사용할 수 있게 준비하세요.",
  "Emergency ambulance / fire": "응급차 / 화재",
  "Use for medical emergency, accident, or fire.": "의료 응급상황, 사고, 화재 시 사용하세요.",
  "Police": "경찰",
  "Use for theft, assault, or immediate safety concerns.": "도난, 폭행, 즉각적인 안전 위협이 있을 때 사용하세요.",
  "Tourist hotline": "관광 통역 안내 1330",
  "Use for travel support, interpretation, or general help.": "여행 지원, 통역, 일반적인 도움을 받을 때 사용하세요.",
  "Police 112": "경찰 112",
  "Ambulance / Fire 119": "구급 / 소방 119",
  "Tourist hotline 1330": "관광 안내 1330",
  "A fast path for the moments foreigners get stuck in Korea: lost items, late-night illness, missed transport, and paperwork panic.": "분실, 심야 몸살, 교통 문제, 서류 마감처럼 외국인이 한국에서 막히는 순간을 빠르게 풀어주는 경로예요.",

  // Data / route / categories
  "Airport rail first": "공항철도 우선",
  "Airport limousine bus": "공항 리무진버스",
  "Taxi direct": "택시 직행",
  "Rail + short taxi": "철도 + 짧은 택시",
  "Official route type": "공식 경로 성격",
  "Flexible fallback": "유연한 대안",
  "Luggage-friendly": "짐 많아도 괜찮아요",
  "Night-friendly": "야간 이동 적합",
  "English-friendly": "영어 가능",
  "Foreigner-ready": "외국인 이용 친화",
  "Support aware": "지원 정보 안내",
  "Reservation ready": "예약 가능",
  "Foreign card OK": "해외 카드 가능",
  "Solo-friendly": "혼자 방문하기 편해요",
  "Safe default": "무난한 기본 선택",
  "Intercity-ready": "도시간 이동에 적합",
  "City-transit fit": "도시 대중교통에 적합",
  "Low-commitment": "부담 적은 선택",
  "Look at intercity rail passes": "도시간 철도 패스 살펴보기",
  "Airport rail, bus, taxi, and the pass that actually fits your Korea trip.": "공항철도, 버스, 택시, 여행에 맞는 패스를 비교하세요.",

  // Explore / assistant / list helpers
  "Need tax refund-friendly stores?": "세금 환급 가능한 매장을 찾고 있나요?",
  "Open Landly Shop for beauty, pharmacy, and souvenir spots with refund-focused guidance.": "뷰티, 약국, 기념품 매장을 환급 중심 가이드와 함께 확인해보세요.",
  "Need care guidance instead of just a place list?": "장소 목록보다 의료 안내가 더 필요하신가요?",
  "Open Landly Care for symptom triage, official support lines, and foreigner-friendly clinic guidance.": "증상 체크, 공식 지원 연락처, 외국인 친화 의료기관 안내를 확인해보세요.",
  "No places found": "장소를 찾지 못했어요",
  "Try adjusting your filters or search terms": "필터나 검색어를 바꿔보세요",
  "No phrases found": "회화 문구가 없어요",

  // Care extra
  "Pharmacy": "약국",
  "Clinic": "의원",
  "Hospital": "병원",
  "Dermatology": "피부과",
  "Dentist": "치과",
  "Checkup": "건강검진",
  "Mental health": "정신건강",
  "Chinese": "중국어",
  "Japanese": "일본어",
  "Specialties": "진료 특성",
  "Official link": "공식 링크",
  "Open map": "지도 열기",
  "Keep a shortlist of foreigner-friendly clinics and pharmacies.": "외국인이 이용하기 쉬운 병원과 약국을 따로 저장해두세요.",
  "Visit prep notes": "방문 준비 메모",
  "Your most recent symptom and question summaries.": "최근 저장한 증상과 질문 메모를 다시 확인하세요.",
  "No saved visit notes yet.": "저장한 방문 준비 메모가 아직 없어요.",
  "Main concern": "주요 증상",
  "Severity": "심각도",
  "User type": "사용자 유형",
  "Traveler": "여행자",
  "Resident": "거주자",
  "Why this result": "이 결과가 나온 이유",
  "Keep the most important information in one place before you go.": "가기 전에 가장 중요한 정보를 한곳에 정리해두세요.",
  "Quick checklist": "빠른 체크리스트",
  "Saved prep notes": "저장한 준비 메모",
  "Re-open the note you last prepared before a visit.": "최근에 작성한 방문 준비 메모를 다시 열어보세요.",
  "No saved notes yet.": "저장한 메모가 아직 없어요.",
  "Official support launcher": "공식 지원 바로가기",
  "Open the most reliable official help routes first.": "가장 신뢰할 수 있는 공식 지원 경로부터 열어보세요.",
  "Call now": "지금 전화하기",
  "Open site": "사이트 열기",

  // Care data / categories
  "health-checkup": "건강검진",
  "mental-health-support": "정신건강 지원",
  "Large tertiary hospital with international patient coordination and multilingual support.": "국제 환자 코디네이션과 다국어 지원을 제공하는 대형 상급종합병원입니다.",
  "English-friendly pharmacy for common cold, stomach care, and travel medicine basics.": "감기, 위장약, 여행 상비약을 영어로 상담받기 쉬운 약국입니다.",
  "Foreigner-friendly skin clinic for consultations, acne care, and cosmetic procedures.": "상담, 여드름 관리, 시술을 받기 쉬운 외국인 친화 피부과입니다.",
  "Dental clinic for urgent pain, scaling, and traveler-friendly dental checkups.": "급한 치통, 스케일링, 여행자용 치과 검진에 적합한 치과입니다.",
  "Support hub for medical tourism, coordination, and checkup/clinic guidance.": "의료관광, 예약 연계, 검진 및 병원 안내를 도와주는 지원 허브입니다.",
  "Counseling-oriented support option for stress, adjustment, and mental health guidance.": "스트레스, 적응 문제, 정신건강 안내를 받을 수 있는 상담 중심 지원 기관입니다.",
  "Useful for urgent but non-catastrophic issues right around airport arrival and departure.": "공항 도착/출발 전후의 비교적 급한 증상에 유용한 의료 지원입니다.",
  "Good option for foreigners needing basic clinic care in central Busan.": "부산 중심에서 기본 진료가 필요한 외국인에게 적합한 선택지입니다.",
  "skin": "피부",
  "laser": "레이저",
  "consultation": "상담",
  "cleaning": "스케일링",
  "stress": "스트레스",
  "adjustment": "적응",
  "counseling": "상담",

  // Shop extra
  "Quick refund check": "빠른 환급 확인",
  "Under 6 months": "6개월 미만",
  "Over 6 months": "6개월 이상",
  "Tourist": "관광객",
  "Temporary stay": "단기 체류",
  "Beauty": "뷰티",
  "Fashion": "패션",
  "Grocery / snacks": "식료품 / 간식",
  "Souvenir": "기념품",
  "Other": "기타",
  "Item status": "상품 상태",
  "Departure timing": "출국 시점",
  "Keep refund notes together until airport day.": "공항 가는 날까지 환급 관련 내용을 한곳에 모아두세요.",
  "No receipts in this status": "이 상태의 영수증이 없어요",
  "Search beauty, pharmacy, gifts...": "뷰티, 약국, 선물 검색…",
  "Immediate": "즉시 환급",
  "General": "일반 환급",
  "No matching stores": "조건에 맞는 매장이 없어요",
  "Passport at checkout": "결제 시 여권 필요",
  "Before you pay": "결제 전에 확인하세요",
  "Ask if tax refund is immediate or handled later.": "세금 환급이 즉시인지, 나중에 처리되는지 확인하세요.",
  "Keep your passport ready if the cashier requests it.": "직원이 요청할 수 있으니 여권을 준비해두세요.",
  "Save the receipt after checkout if refund is still pending.": "환급이 아직 완료되지 않았다면 결제 후 영수증을 저장해두세요.",
  "Departure refund checklist": "출국 전 환급 체크리스트",
  "Departure date": "출국일",
  "Open refund guide": "환급 가이드 열기",
  "duty-free": "면세점",
  "department-store": "백화점",
  "convenience": "편의점",
  "Large flagship-style beauty store with common tourist brands and quick checkout support.": "관광객이 많이 찾는 브랜드와 빠른 결제를 지원하는 대형 뷰티 매장입니다.",
  "Popular stop for skincare, masks, and travel-sized items near youth shopping streets.": "젊은 상권 근처에서 스킨케어, 마스크팩, 여행용 제품을 사기 좋은 매장입니다.",
  "Major downtown duty-free store for beauty, fashion, and packaged souvenirs.": "뷰티, 패션, 포장 기념품을 살 수 있는 도심 대표 면세점입니다.",
  "Department store with fashion, beauty, and concierge-style tourist support.": "패션, 뷰티와 관광객 안내 서비스를 제공하는 백화점입니다.",
  "Traditional-style souvenirs, stationery, and small gifts for family and coworkers.": "가족과 동료를 위한 전통풍 기념품, 문구, 작은 선물을 사기 좋은 곳입니다.",
  "Convenience store useful for snacks, packaged gifts, and last-minute daily needs.": "간식, 포장 선물, 급한 생활용품을 사기 좋은 편의점입니다.",
  "Convenient stop for OTC items, masks, supplements, and practical short-stay purchases.": "일반의약품, 마스크, 영양제, 단기체류용 실용 제품을 사기 편한 곳입니다.",
  "Trend-focused beauty stop near cafes and popup-heavy shopping streets.": "카페와 팝업이 많은 거리 근처의 트렌디한 뷰티 매장입니다.",
  "K-beauty": "K-뷰티",
  "luxury": "럭셔리",
  "voucher": "바우처",
  "premium": "프리미엄",
  "gifts": "선물",
  "handmade": "핸드메이드",
  "traditional": "전통",
  "gift": "선물",
  "snacks": "간식",
  "OTC": "일반의약품",
  "health": "건강",
  "essentials": "필수품",
  "trend route": "트렌드 코스",

  // Stay extra
  "Do these first": "먼저 할 일",
  "Later this month": "이번 달 안에 하기",
  "Keep in mind": "참고할 점",
  "Official resources": "공식 자료",
  "Open official routes first whenever the process affects visa, insurance, tax, or labor status.": "비자, 보험, 세금, 근로 상태에 영향을 주는 절차는 항상 공식 경로부터 확인하세요.",
  "Add a document note": "문서 메모 추가",
  "e.g. ARC appointment receipt": "예: 외국인등록증 예약 접수증",
  "What is this for? When will you need it?": "이 문서는 어디에 쓰나요? 언제 필요하나요?",
  "No document notes yet.": "문서 메모가 아직 없어요.",
  "Plan builder": "계획 설정",
  "Stay type": "체류 유형",
  "Entry date": "입국일",
  "Region": "지역",
  "Housing status": "주거 상태",
  "Secured": "확정됨",
  "Temporary": "임시 거주",
  "Searching": "찾는 중",
  "Seoul": "서울",
  "A calmer mission flow for your first three months in Korea": "한국 첫 3개월을 더 차분하게 정리할 수 있는 미션 플로우",
  "This mission view works best after you decide your stay type. Use it to avoid discovering official deadlines too late.": "체류 유형을 정한 뒤 보면 가장 좋습니다. 공식 마감일을 너무 늦게 알게 되는 일을 줄여보세요.",
  "Days 1–7": "1–7일",
  "Stabilize the things that block everything else.": "다른 일을 막는 핵심 요소부터 안정화하세요.",
  "Days 8–30": "8–30일",
  "Turn your setup into a repeatable routine.": "초기 준비를 반복 가능한 루틴으로 바꾸세요.",
  "Days 31–90": "31–90일",
  "Review the legal and practical pieces before they become urgent.": "급해지기 전에 법적·실무적 요소를 다시 확인하세요.",
  "missions": "개 미션",
  "Mark stay mission incomplete": "체류 미션 완료 취소",
  "Mark stay mission complete": "체류 미션 완료 표시",
  "Open related step": "관련 단계 열기",
  "Category:": "카테고리:",
  "Plan, save, and jump into official help without guessing the next step.": "다음 단계를 고민하지 않고 계획·저장·공식 도움 이동까지 이어가세요.",
  "Need official support?": "공식 지원이 필요하신가요?",
  "Open official routes for immigration, Seoul support, or local resident guidance.": "출입국, 서울시 지원, 지역 외국인 주민 지원 경로를 바로 열어보세요.",
  "Need a first step?": "무엇부터 해야 할지 막막한가요?",
  "Start with the plan builder, then review deadlines and save the documents you will actually need.": "먼저 계획 설정을 한 뒤, 마감일을 확인하고 실제로 필요한 문서를 저장하세요.",
  "Alien Registration Card (ARC)": "외국인등록증(ARC)",
  "Required for foreigners staying over 90 days. Must apply within 90 days of arrival.": "90일 초과 체류 외국인에게 필요하며, 입국 후 90일 이내 신청해야 해요.",
  "Passport photo (3.5×4.5cm)": "여권사진(3.5×4.5cm)",
  "Proof of address": "주소 증빙",
  "Book an appointment online in advance at HiKorea.": "HiKorea에서 미리 온라인 예약을 하세요.",
  "Bring original documents, not copies.": "사본이 아니라 원본 서류를 챙기세요.",
  "Fees: KRW 30,000 for first issuance.": "최초 발급 수수료는 3만 원입니다.",
  "Learn your basic tax timeline": "기본 세금 일정 이해하기",
  "Understand when year-end tax adjustment or local tax reminders may matter for your stay.": "연말정산이나 지방세 안내가 언제 중요한지 미리 이해해두세요.",
  "Employment or student status": "재직 또는 학생 상태",
  "Income note if available": "소득 관련 자료(있다면)",
  "Use official guides first and ask for help when unsure.": "공식 가이드를 먼저 보고, 헷갈리면 도움을 요청하세요.",
  "Keep employment or school documents easy to find.": "재직·학교 관련 서류를 쉽게 찾을 수 있게 보관하세요.",
  "Save your support contacts": "지원 연락처 저장",
  "Bookmark immigration, insurance, and local foreign resident support channels before you need them.": "필요해지기 전에 출입국, 보험, 외국인 지원 연락처를 저장해두세요.",
  "Store at least one immigration and one local support contact.": "출입국 연락처와 지역 지원 연락처를 최소 하나씩 저장하세요.",
  "Check whether your district has a dedicated foreign resident center.": "거주 지역에 외국인 주민 전용 센터가 있는지 확인하세요.",

  // Promotions / stamps / more data
  "Keep your trip admin, receipts, health, and help close at hand.": "여행 일정, 영수증, 건강, 긴급 도움을 한곳에서 빠르게 관리하세요.",
  "Living in Korea": "한국 생활",
  "Organize long-stay tasks and your saved profile tools.": "장기체류 준비와 저장한 개인 도구를 정리하세요.",
  "See your saved route plans and daily events.": "저장한 이동 계획과 일정을 한눈에 확인하세요.",
  "Track official goals and your own Korea achievements.": "공식 목표와 나만의 한국 생활 목표를 함께 관리하세요.",
  "Current and upcoming events, interest, booking, and saved schedules.": "진행 중이거나 예정된 이벤트를 보고 관심, 예약, 일정 저장까지 관리하세요.",
  "Tax refund, receipt locker, and store discovery.": "세금 환급, 영수증 보관, 매장 찾기를 한 번에 이용하세요.",
  "Medical triage, clinics, and pharmacy help.": "증상 체크, 병원·약국 찾기, 의료 도움 기능을 제공합니다.",
  "Fast access to emergency numbers and help actions.": "긴급 전화와 도움 기능에 빠르게 접근하세요.",

  // Misc
  "Required documents": "필요 서류",
  "Tips": "팁",
  "Official links": "공식 링크",
  "Choose": "선택",
  "Cost": "비용",
  "Speed": "속도",
  "plan": "계획",

  // Additional runtime strings
  "This is not a diagnosis. It helps point you to the safest next step.": "이 기능은 진단이 아니라, 더 안전한 다음 행동을 안내해줍니다.",
  "Cold / fever": "감기 / 열",
  "Stomach": "복통",
  "Dental": "치과",
  "Injury": "부상",
  "Stress / mental health": "스트레스 / 정신건강",
  "Breathing issue": "호흡 곤란",
  "Heavy bleeding": "심한 출혈",
  "Chest pain": "가슴 통증",
  "Night time": "야간",
  "If you feel unsafe or your symptoms are suddenly severe, use emergency help first.": "위험하다고 느끼거나 증상이 갑자기 심해지면 먼저 긴급 도움을 이용하세요.",
  "Call 119": "119 전화",
  "Call 1339": "1339 전화",
  "Call 1330": "1330 전화",
  "Find a pharmacy": "약국 찾기",
  "Find a clinic": "병원 찾기",
  "Find specialist care": "전문 진료 찾기",
  "Symptoms": "증상",
  "Allergies": "알레르기",
  "Current medicines": "현재 복용약",
  "Questions": "질문",
  "Insurance / payment note": "보험 / 결제 메모",
  "Save prep note": "준비 메모 저장",
  "Copy summary": "요약 복사",
  "Bring passport or ID": "여권 또는 신분증 챙기기",
  "Prepare payment or insurance details": "결제 또는 보험 정보 준비하기",
  "List your current medicines": "현재 복용 중인 약 적어두기",
  "List allergies or reactions": "알레르기나 이상 반응 적어두기",
  "Note when symptoms started": "증상이 시작된 시점 적어두기",
  "Write down questions for the doctor": "의사에게 물어볼 질문 적어두기",
  "Check if interpretation help is needed": "통역 도움이 필요한지 확인하기",
  "Save this store": "이 매장 저장",
  "Saved store": "저장한 매장",
  "Add receipt later": "나중에 영수증 추가",
  "Show shopping phrases": "쇼핑 회화 보기",
  "Stay length": "체류 기간",
  "Resident status": "체류 상태",
  "Purchase amount (KRW)": "구매 금액 (원)",
  "Opened / used": "개봉 / 사용함",
  "Unopened": "미개봉",
  "Leaving within 3 months": "3개월 이내 출국",
  "Later than 3 months": "3개월 이후 출국",
  "Likely eligible": "환급 가능성이 높아요",
  "Not eligible": "환급 대상이 아니에요",
  "Check in store": "매장에서 확인 필요",
  "Find stores": "매장 찾기",
  "Save receipt": "영수증 저장",
  "View guide": "가이드 보기",
  "Receipt saved to locker.": "영수증을 보관함에 저장했어요.",
  "Add receipt": "영수증 추가",
  "Receipt marked as done.": "영수증을 완료 처리했어요.",
  "Receipt moved to needs check.": "영수증을 확인 필요 상태로 옮겼어요.",
  "Receipt removed.": "영수증을 삭제했어요.",
  "Delete": "삭제",
  "Unlinked receipt": "연결되지 않은 영수증",
  "Mark done": "완료 표시",
  "Needs check": "확인 필요",
  "Bring your passport and check stored receipts.": "여권을 챙기고 저장한 영수증을 다시 확인하세요.",
  "Keep eligible items unopened until departure.": "환급 대상 상품은 출국 전까지 개봉하지 마세요.",
  "Allow extra airport time if you still need to process general refund steps.": "일반 환급 절차가 남아 있다면 공항에서 여유 시간을 더 잡으세요.",
  "Check whether your refund can be handled downtown, kiosk, or airport counter.": "도심, 키오스크, 공항 창구 중 어디서 환급 처리되는지 확인하세요.",
  "Review baggage and customs order before you queue.": "줄 서기 전에 수하물과 세관 절차 순서를 다시 확인하세요.",
  "Set your departure date and keep an eye on any receipt still marked pending.": "출국일을 설정하고 아직 대기 중인 영수증이 있는지 확인하세요.",
  "Your {stayTypeLabel} setup plan for {city}. Focus on the next official step, not ten open tabs.": "{city}에서의 {stayTypeLabel} 준비 계획입니다. 여러 탭을 헤매기보다 다음 공식 절차에 집중하세요.",
  "Choose the closest stay profile so Landly can surface the right first steps.": "가장 가까운 체류 유형을 선택하면 Landly가 먼저 해야 할 일을 더 정확히 보여줄 수 있어요.",
  "Student": "학생",
  "Worker": "직장인",
  "Working holiday": "워킹홀리데이",
  "Long stay": "장기체류",
  "School linked": "학교 연동됨",
  "Employer linked": "직장 연동됨",
  "With family": "가족 동반",
  "Save the file name, purpose, and any important date even if the document itself lives in email, cloud storage, or paper.": "문서 원본이 이메일, 클라우드, 종이로 따로 있어도 파일명, 용도, 중요한 날짜를 메모해두세요.",
  "Save document note": "문서 메모 저장",
  "Issued": "발급일",
  "Expires": "만료일",
  "Housing safety": "주거 안전",
  "Before signing or paying a deposit, bookmark an official housing support route and keep your contract notes together.": "계약하거나 보증금을 보내기 전에 공식 주거 지원 경로를 저장하고 계약 메모를 함께 보관하세요.",
  "Work, tax, and insurance basics": "근로·세금·보험 기본",
  "Start from official routes when your visa, job status, insurance, or tax timeline could be affected.": "비자, 직장 상태, 보험, 세금 일정에 영향이 있을 수 있다면 공식 경로부터 확인하세요.",
  "Keep official immigration, NHIS, student, and resident support routes one tap away.": "출입국, 건강보험, 학생 지원, 주민 지원 경로를 한 번에 열 수 있게 준비하세요.",
  "This week": "이번 주",
  "Soon": "곧 확인",
  "Don't forget": "잊지 마세요",
  "Track first 90 days": "첫 90일 추적",
  "See the missions most likely to unblock your setup fast.": "정착을 빠르게 풀어줄 가능성이 높은 미션을 확인하세요.",
  "Build my plan": "내 계획 만들기",
  "Turn your stay type into the next tasks that matter.": "체류 유형에 맞는 다음 할 일을 정리하세요.",
  "Check deadlines": "마감일 확인",
  "Registration, housing, insurance, tax, and support basics.": "등록, 주거, 보험, 세금, 지원 기본 항목을 확인하세요.",
  "Save documents": "문서 저장",
  "Keep contract, passport, insurance, and school/work notes together.": "계약서, 여권, 보험, 학교/직장 메모를 함께 정리하세요.",
  "Find official help": "공식 도움 찾기",
  "Jump to immigration, NHIS, student, housing, and labor support.": "출입국, 건강보험, 학생, 주거, 노동 지원으로 바로 이동하세요.",
  "passport": "여권",
  "residence": "거주",
  "contract": "계약",
  "insurance": "보험",
  "school": "학교",
  "work": "근무",
  "tax": "세금",


  "Check symptoms": "증상 확인",
  "Understand the next best step without guessing.": "추측하지 말고 다음 행동을 빠르게 판단하세요.",
  "Find clinic or pharmacy": "병원·약국 찾기",
  "Search foreigner-friendly providers by type and language.": "진료 유형과 언어 기준으로 외국인 친화 의료기관을 찾아보세요.",
  "Medical phrases": "의료 회화",
  "Show symptoms, allergies, and reception questions quickly.": "증상, 알레르기, 접수 관련 질문을 빠르게 보여주세요.",
  "Official support lines": "공식 지원 연락처",
  "Open 119, 1339, 1330, and support resources from one place.": "119, 1339, 1330과 공식 지원 정보를 한곳에서 여세요.",
  "Find tax refund shops": "환급 가능한 매장 찾기",
  "Immediate and general refund-friendly stores in one place.": "즉시 환급과 일반 환급 매장을 한곳에서 보세요.",
  "Check refund eligibility": "환급 가능 여부 확인",
  "See if a purchase likely qualifies before you pay.": "결제 전에 환급 가능성을 먼저 확인하세요.",
  "Save shopping receipts": "쇼핑 영수증 저장",
  "Keep pending and completed refund notes together.": "대기 중이거나 완료된 환급 메모를 함께 보관하세요.",
  "Hi Korea & 1345": "Hi Korea & 1345",
  "Use for immigration basics, electronic civil applications, and multilingual immigration guidance.": "출입국 기본 정보, 전자 민원, 다국어 안내를 확인할 때 이용하세요.",
  "NHIS foreign resident guide": "국민건강보험 외국인 안내",
  "Start here for foreign resident health insurance basics and official NHIS support.": "외국인 건강보험 기본 정보와 공식 지원 안내를 확인할 때 시작하기 좋아요.",
  "Study in Korea": "Study in Korea",
  "Student-focused visa, school, housing, and 생활 information in one place.": "유학생을 위한 비자, 학교, 주거, 생활 정보를 한곳에서 확인하세요.",
  "Seoul global portal": "서울 글로벌 포털",
  "City-level living, tax, labor, counseling, and resident support information for Seoul.": "서울 생활, 세금, 노동, 상담, 외국인 지원 정보를 한곳에서 확인하세요.",
  "Housing & real estate support": "주거 / 부동산 지원",
  "Use official housing and real-estate guidance before signing a contract or paying a deposit.": "계약서 작성이나 보증금 지급 전에 공식 주거·부동산 정보를 먼저 확인하세요.",
  "Tax & local resident basics": "세금 / 주민 생활 기초",
  "Start with official tax guidance before acting on community advice or social media posts.": "커뮤니티 조언이나 SNS 정보보다 먼저 공식 세금 안내를 확인하세요.",
  "Labor counseling & basics": "노동 상담 / 기본 안내",
  "Understand contract basics, work conditions, and where to ask for help when something feels off.": "계약 기본, 근로 조건, 문제가 생겼을 때 어디에 도움을 요청할지 미리 알아두세요.",

  // v06 globalization finish
  "My own Korea goal": "내 한국 생활 목표",
  "Korea Local Pro": "한국 생활 프로",
  "Seoul Comfort Level": "서울 적응 완료",
  "Korea Explorer": "코리아 탐험가",
  "Arrival Starter": "도착 스타터",
  "Saved stay resources": "저장한 정착 지원 리소스",
  "Official help routes you've bookmarked for later.": "나중에 다시 볼 공식 지원 경로를 저장해두었습니다.",
  "No saved stay resources yet": "저장한 정착 리소스가 아직 없어요",
  "Bookmark immigration, insurance, housing, or labor resources in Landly Stay.": "Landly Stay에서 출입국, 보험, 주거, 노동 관련 리소스를 저장해보세요.",
  "What to do now": "지금 바로 할 일",
  "urgent": "긴급",

  // Home / action cards
  "Get from the airport smoothly": "공항에서 시내까지 편하게 이동하기",
  "Open the SOS support hub": "SOS 도움 허브 열기",
  "Find a place to eat nearby": "근처 식사 장소 찾기",
  "Use Korean help phrases": "한국어 도움 문구 사용하기",
  "Check tax refund eligibility": "세금 환급 가능 여부 확인",
  "Save receipts before departure": "출국 전 영수증 저장하기",
  "Find a clinic or pharmacy": "병원이나 약국 찾기",
  "Register as a foreigner": "외국인 등록 준비하기",
  "Find tax refund stores": "환급 가능한 매장 찾기",
  "Open your Korea calendar": "한국 일정 캘린더 열기",
  "Emergency help": "긴급 도움",
  "Build your Korea setup plan": "한국 생활 준비 플랜 만들기",
  "Set up a Korean SIM": "한국 유심 설정하기",
  "Visit a pharmacy": "약국 방문하기",
  "Housing, tax, and labor guides": "주거·세금·노동 가이드",
  "Collect seasonal Korea stamps": "계절별 한국 스탬프 모으기",
  "Open a bank account": "은행 계좌 개설하기",
  "Compare rail, bus, taxi, and pass options before you leave the terminal.": "터미널을 나가기 전에 철도, 버스, 택시, 패스 옵션을 비교하세요.",
  "Lost item, late-night illness, missed train, or paperwork panic? Start from one fast rescue flow.": "분실, 야간 아픔, 막차 문제, 서류 마감이 걱정될 때 빠른 구조 플로우로 시작하세요.",
  "Show taxi, restaurant, emergency, and hospital phrases quickly.": "택시, 식당, 응급, 병원 문구를 빠르게 보여주세요.",
  "See if your purchase and stay status likely qualify before checkout.": "결제 전에 구매 내역과 체류 상태로 환급 가능성을 먼저 확인하세요.",
  "Keep refund notes together before you head to the airport.": "공항 가기 전에 환급 관련 메모를 한곳에 모아두세요.",
  "Check multilingual clinics, pharmacies, and official support lines.": "다국어 지원 병원, 약국, 공식 지원 연락처를 확인하세요.",
  "ARC registration is required for stays over 90 days.": "90일 이상 체류라면 외국인등록이 필요해요.",
  "Open stores with foreign-card support and clear refund options.": "외국 카드 사용 가능 여부와 환급 옵션이 명확한 매장을 확인하세요.",
  "Keep saved arrival plans and first-week admin dates together.": "저장한 도착 계획과 첫 주 행정 일정을 함께 관리하세요.",
  "Police 112 · Fire & ambulance 119 · Tourist hotline 1330.": "경찰 112 · 소방/구급 119 · 관광 통역 1330",
  "Turn your stay type into a clear, step-by-step setup flow.": "체류 유형에 맞춰 준비해야 할 일을 단계별로 정리하세요.",
  "Compare carriers and get connected within minutes.": "통신사를 비교하고 빠르게 연결하세요.",
  "Find open pharmacies and explain your symptoms in Korean.": "열려 있는 약국을 찾고 증상을 한국어로 설명해보세요.",
  "Official support routes for the things that affect your visa and legal status.": "비자와 체류 상태에 영향을 주는 일은 공식 지원 경로부터 확인하세요.",
  "Earn visit stamps from saved plans and level up your Landly profile.": "저장한 계획으로 방문 스탬프를 모으고 Landly 레벨을 올리세요.",
  "Step-by-step guide to opening an account as a foreigner.": "외국인 계좌 개설 과정을 단계별로 안내합니다.",
  "emergency": "긴급",
  "food": "음식",
  "lifestyle": "생활",
  "admin": "행정",

  // Pass / first72 data
  "Save your airport route before the plane lands": "비행기가 도착하기 전에 공항 경로 저장하기",
  "Prepare the phrases you will need first": "먼저 필요한 회화 준비하기",
  "Check which transport option fits your real condition": "내 실제 상황에 맞는 교통수단 확인하기",
  "Open the exact map route you chose": "선택한 정확한 지도 경로 열기",
  "Keep one pharmacy or clinic backup nearby": "가까운 약국이나 병원을 하나 미리 확보하기",
  "Save your lodging area and nearest landmark": "숙소 지역과 가까운 랜드마크 저장하기",
  "Decide if you need a transit card or simple pay-as-you-go": "교통카드가 필요한지 판단하기",
  "Pin the places you will revisit": "다시 갈 장소 저장하기",
  "Move your confirmed plans into Calendar": "확정한 계획을 캘린더로 옮기기",
  "Bookmark one SOS fallback flow": "대비용 SOS 흐름 하나 저장하기",
  "Lock in one route, one backup route, and the area name you need to show a driver.": "기본 경로 하나, 대체 경로 하나, 기사에게 보여줄 지역명을 미리 정하세요.",
  "Keep taxi, station, lost-item, and emergency phrases ready for fast use.": "택시, 역, 분실, 응급 관련 회화를 바로 쓸 수 있게 준비하세요.",
  "Heavy luggage, children, late-night arrival, and long immigration lines can change the best route.": "큰 짐, 아이 동반, 심야 도착, 긴 입국 심사 대기가 최적 경로를 바꿀 수 있어요.",
  "Use the route picker once instead of searching from zero outside the airport.": "공항 밖에서 처음부터 다시 검색하지 말고, 고른 경로를 바로 여세요.",
  "Jet lag, stomach issues, and sudden fever happen most often on the first night.": "시차, 복통, 갑작스런 열은 첫날 밤에 자주 생겨요.",
  "If you get turned around, the area name matters more than the full address.": "길을 잃었을 때는 전체 주소보다 지역명이 더 도움이 될 수 있어요.",
  "Make the decision after your first real ride, not only from guesswork.": "막연히 정하지 말고 첫 실제 이동 후에 결정해도 괜찮아요.",
  "Save your hotel, station, pharmacy, and one food stop so you can reopen them fast.": "호텔, 역, 약국, 음식점 한 곳은 저장해두면 다시 열기 쉬워요.",
  "Keep transport, check-in, shopping, and care-related plans in one place.": "이동, 체크인, 쇼핑, 의료 관련 계획을 한곳에 모아두세요.",
  "Lost item, missed last train, and emergency support should stay one tap away.": "분실, 막차 놓침, 응급 도움은 한 번의 탭으로 열 수 있게 해두세요.",
  "Especially useful after long flights or late arrivals.": "장거리 비행이나 늦은 도착 후에 특히 유용해요.",

  // Places / providers / stores / proper names
  "Severance Hospital International Health Care Center": "세브란스병원 국제진료센터",
  "ON THE SPOT Pharmacy Itaewon": "온더스팟 약국 이태원점",
  "Gangnam Aesthetic Dermatology Clinic": "강남 에스테틱 피부과",
  "Seoul Smile Dental Center": "서울 스마일 치과",
  "Seoul Medical Tourism Support Center": "서울의료관광지원센터",
  "Mind Link Global Counseling Support": "마인드링크 글로벌 상담 지원",
  "Incheon Airport Emergency Medical Center": "인천공항 응급의료센터",
  "Busan International Clinic": "부산 국제 클리닉",
  "Seodaemun-gu, Seoul": "서울 서대문구",
  "Yongsan-gu, Seoul": "서울 용산구",
  "Gangnam-gu, Seoul": "서울 강남구",
  "Jung-gu, Seoul": "서울 중구",
  "Jongno-gu, Seoul": "서울 종로구",
  "Incheon Airport": "인천공항",
  "Dong-gu, Busan": "부산 동구",
  "Emergency 119": "응급 119",
  "Medical hotline 1339": "의료 상담 1339",
  "Tourist helpline 1330": "관광안내 1330",
  "Medical Korea Support Center": "메디컬코리아 지원센터",
  "Seoul Medical Tourism Center": "서울의료관광지원센터",
  "Seoul Global Center": "서울글로벌센터",
  "Emergency ambulance / rescue for urgent situations.": "긴급 상황에서 구급차·구조 지원을 요청할 수 있어요.",
  "Medical and infectious disease guidance line.": "의료·감염병 관련 상담을 받을 수 있어요.",
  "Travel interpretation and multilingual support.": "여행 통역과 다국어 지원을 받을 수 있어요.",
  "Official support for foreign patients and interpretation guidance.": "외국인 환자를 위한 공식 지원과 통역 안내를 제공합니다.",
  "Interpretation and medical tourism support in Seoul.": "서울에서 통역과 의료관광 지원을 받을 수 있어요.",
  "Foreign resident support including everyday life guidance.": "외국인 주민을 위한 생활 전반의 지원 정보를 제공합니다.",
  "phone": "전화",
  "web": "웹",
  "Tosokchon Samgyetang": "토속촌 삼계탕",
  "Cafe Bora": "카페 보라",
  "Severance Hospital International Health Care": "세브란스병원 국제진료",
  "GS25 Itaewon": "GS25 이태원점",
  "KEB Hana Bank Currency Exchange": "KEB하나은행 환전",
  "Gyeongbokgung Palace": "경복궁",
  "Lotte Mart Seoul Station": "롯데마트 서울역점",
  "AREX Seoul Station Travel Center": "AREX 서울역 여행센터",
  "Incheon Airport Bus Information Desk": "인천공항 버스 안내데스크",
  "Busan Station Travel Center": "부산역 여행센터",
  "Famous ginseng chicken soup restaurant near Gyeongbokgung. English menu available.": "경복궁 근처의 유명한 삼계탕집으로 영어 메뉴를 제공합니다.",
  "Full international patient services with English-speaking doctors.": "영어 진료가 가능한 국제환자 전용 서비스를 제공합니다.",
  "24/7 convenience store with international items and ATM.": "해외 결제와 ATM 이용이 편한 24시간 편의점입니다.",
  "Airport currency exchange with competitive rates and multiple currencies.": "다양한 통화를 지원하는 공항 환전소입니다.",
  "Main royal palace of Joseon dynasty. English audio guide available.": "조선의 대표 궁궐로 영어 오디오 가이드가 있습니다.",
  "English-speaking staff, wide range of OTC medicine and supplements.": "영어 응대가 가능하고 일반의약품과 영양제가 다양합니다.",
  "Large supermarket with tax refund service. Great for K-food and snacks.": "세금 환급이 가능한 대형마트로 K-푸드와 간식 쇼핑에 좋습니다.",
  "Airport Express and rail information counter with ticketing support for travelers.": "공항철도와 일반 철도 안내 및 발권 지원을 제공합니다.",
  "Bus routes, city airport limousine information, and multilingual help near arrivals.": "도착장 근처에서 버스 노선, 공항 리무진, 다국어 안내를 제공합니다.",
  "Foreigner support center for transit, living help, interpretation, and official guidance.": "교통, 생활, 통역, 공식 안내를 제공하는 외국인 지원 센터입니다.",
  "Useful stop for KTX arrivals, regional rail connections, and ticket support.": "KTX 도착, 지역 철도 환승, 발권 지원에 유용한 거점입니다.",
  "Incheon": "인천",
  "Busan": "부산",
  "cafe": "카페",
  "exchange": "환전",
  "sightseeing": "관광",

  // Stay checklist/resources
  "Korean SIM / Phone Plan": "한국 SIM / 요금제",
  "T-money / Cashbee Card": "티머니 / 캐시비 카드",
  "Open a Korean Bank Account": "한국 은행 계좌 개설",
  "Enroll in National Health Insurance (NHIS)": "국민건강보험(NHIS) 가입",
  "Register Your Address (Resident Registration)": "주소 등록",
  "Register for Korean Language Classes": "한국어 수업 등록",
  "Set up a local number for banking, apps, and everyday use.": "은행, 앱, 일상생활에 필요한 현지 번호를 준비하세요.",
  "Rechargeable transit card for subway, bus, and some taxis.": "지하철, 버스, 일부 택시에서 쓸 수 있는 충전식 교통카드예요.",
  "Needed for salary deposits, bill payments, and Korean apps.": "급여 입금, 요금 납부, 한국 앱 사용에 필요해요.",
  "Foreigners staying over 6 months must enroll. Covers most medical costs.": "6개월 이상 체류 외국인은 가입해야 하며, 대부분의 의료비를 보장해요.",
  "Required for banking, insurance, and official communications.": "은행, 보험, 공식 안내 수신에 필요해요.",
  "TOPIK preparation and general Korean language courses.": "TOPIK 준비와 일반 한국어 수업을 찾아볼 수 있어요.",
  "HiKorea Appointment": "HiKorea 예약",
  "HelloMobile": "헬로모바일",
  "KakaoBank": "카카오뱅크",
  "NHIS Foreign Language Support": "NHIS 외국어 지원",
  "King Sejong Institute": "세종학당",
  "Hi Korea": "하이코리아",
  "registration": "등록",
  "telecom": "통신",
  "banking": "금융",
  "healthcare": "의료",
  "housing": "주거",
  "work_school": "직장 / 학교",
  "support": "지원",
  "Decide which official registration items apply to you": "내게 필요한 공식 등록 항목 확인하기",
  "Lock in housing proof, contract notes, and move-in details": "주거 증빙, 계약 메모, 입주 정보를 정리하기",
  "Open your telecom + bank setup checklist": "통신 + 은행 준비 체크리스트 열기",
  "Finish healthcare and insurance basics": "건강관리와 보험 기본 준비 마치기",
  "Set up recurring admin reminders": "반복되는 행정 리마인더 설정하기",
  "Check job, student, or support-center routes that match your stay type": "체류 유형에 맞는 취업·학업·지원센터 경로 확인하기",
  "Review tax, labor, and resident basics before the 3-month mark": "3개월 전 세금·노동·거주 기본사항 점검하기",
  "Archive your important Korea documents with expiry dates": "만료일과 함께 중요한 문서 보관하기",
  "Use your stay type and entry timing to decide what cannot wait beyond the first week.": "체류 유형과 입국 시점에 따라 첫 주 안에 처리해야 할 항목을 확인하세요.",
  "Keep the documents that prove where you live before you need them for another process.": "다른 절차에 필요해지기 전에 거주를 증명할 자료를 미리 정리해두세요.",
  "These are the two most common blockers for longer stays and everyday payments.": "장기체류와 일상 결제에서 가장 자주 막히는 두 가지예요.",
  "Know what is official, what is optional, and where to get verified help when something feels unclear.": "무엇이 공식 절차인지, 무엇이 선택사항인지, 헷갈릴 때 어디서 확인해야 하는지 파악하세요.",
  "Documents, renewals, and school or employer requests become easier once they live in one reminder center.": "문서, 갱신 일정, 학교·직장 요청 사항을 한 리마인더 센터에 모아두면 훨씬 관리가 쉬워져요.",
  "Use official help routes early before relying on social posts or fragmented advice.": "커뮤니티 글이나 단편적인 정보에 의존하기 전에 공식 경로를 먼저 확인하세요.",
  "This is the point where small misunderstandings can become expensive or stressful later.": "이 시점의 작은 오해가 나중엔 비용이나 스트레스로 이어질 수 있어요.",
  "Keep expiry and issue dates visible now so you are not rebuilding this later under pressure.": "발급일과 만료일을 지금 보이게 정리해두면 나중에 급하게 다시 찾지 않아도 돼요.",
  "immigration": "출입국",
  "nhis": "건강보험",
  "support-center": "지원센터",
  "labor": "노동",

  // Promotions / stamps / shop / pass / SOS data
  "Open taxi app": "택시 앱 열기",
  "Open rail booking": "철도 예약 열기",
  "Open tourist help": "관광 지원 열기",
  "Open transit guide": "교통 가이드 열기",
  "Enter your date, origin, and destination, then save that route to Calendar.": "날짜, 출발지, 도착지를 입력하고 경로를 캘린더에 저장하세요.",
  "Move to a taxi booking flow after you decide the route.": "경로를 정한 뒤 택시 호출 흐름으로 이동하세요.",
  "Use this when you plan intercity travel after arrival.": "도착 후 도시 간 이동을 계획할 때 이용하세요.",
  "Use this when your travel plan changes or you need help.": "여행 계획이 바뀌었거나 도움이 필요할 때 사용하세요.",
  "Check Seoul transit cards and travel cards before purchase.": "구매 전 서울 교통카드와 여행 패스를 비교해보세요.",
  "taxi": "택시",
  "rail": "철도",
  "Olive Young Myeongdong Town": "올리브영 명동타운점",
  "LOHB's Hongdae": "롭스 홍대점",
  "Lotte Duty Free Main Store": "롯데면세점 본점",
  "Shinsegae Department Store Gangnam": "신세계백화점 강남점",
  "Insadong Craft House": "인사동 공예 하우스",
  "CU Myeongdong Central": "CU 명동중앙점",
  "Onnuri Pharmacy Myeongdong": "온누리약국 명동점",
  "Olive Young Seongsu": "올리브영 성수점",
  "Myeong-dong": "명동",
  "Hongdae": "홍대",
  "Sogong-dong": "소공동",
  "Gangnam": "강남",
  "Insadong": "인사동",
  "Seongsu": "성수",
  "Korea Grand Sale shopping perks": "코리아그랜드세일 쇼핑 혜택",
  "Olive Young tourist coupon page": "올리브영 관광객 쿠폰 페이지",
  "Duty free welcome voucher": "면세점 웰컴 바우처",
  "shopping-festival": "쇼핑 페스티벌",
  "Beginner K-beauty route": "초보자용 K-뷰티 코스",
  "Trend shopping route": "트렌드 쇼핑 코스",
  "Seoul Spring Night Market Picks": "서울 봄 야시장 추천",
  "K-culture intro walk for first-time visitors": "첫 방문자를 위한 K-컬처 입문 산책",
  "Busan coastal weekend event watch": "부산 해변 주말 이벤트 가이드",
  "Neighborhood food class and market stop": "동네 음식 클래스와 시장 코스",
  "A curated list of foreigner-friendly booths, food, and late-night stops near the Han River.": "한강 근처에서 외국인이 즐기기 쉬운 부스, 음식, 야간 코스를 모았습니다.",
  "An easy evening route covering one palace area, one photo stop, and one local snack stop.": "궁궐 한 곳, 사진 명소 한 곳, 간식 코스 한 곳을 잇는 가벼운 저녁 루트입니다.",
  "Save the best viewpoints, backup transit routes, and weather-aware plan for a crowded weekend event.": "혼잡한 주말 이벤트를 위해 전망 포인트, 백업 교통 경로, 날씨 대응 계획을 함께 정리하세요.",
  "A small group session focused on market etiquette, ingredient basics, and easy Korean food words.": "시장 예절, 식재료 기본, 쉬운 한국 음식 표현을 배우는 소규모 클래스입니다.",
  "Yeouido Hangang area": "여의도 한강 일대",
  "Gyeongbokgung → Bukchon → Insadong": "경복궁 → 북촌 → 인사동",
  "Gwanganri area": "광안리 일대",
  "Mangwon Market area": "망원시장 일대",
  "festival": "축제",
  "tour": "투어",
  "class": "클래스",
  "Lost phone or wallet": "휴대폰이나 지갑을 잃어버렸어요",
  "Sick late at night": "밤늦게 몸이 아파요",
  "Missed the last train": "막차를 놓쳤어요",
  "Paperwork deadline is close": "서류 마감이 얼마 남지 않았어요",
  "Call police 112": "112 경찰에 전화하기",
  "Lost item phrases": "분실 대응 문구",
  "Support lines": "지원 연락처",
  "Open symptom triage": "증상 체크 열기",
  "Find pharmacy": "약국 찾기",
  "Call ambulance 119": "119 구급차 부르기",
  "Open taxi phrases": "택시 문구 열기",
  "Open Pass launchers": "패스 바로가기 열기",
  "Open Stay plan": "스테이 플랜 열기",
  "Open document vault": "문서 보관함 열기",
  "Open guides": "가이드 열기",
  "Try kimchi in Korea": "한국에서 김치 먹어보기",
  "Late-night convenience store run": "심야 편의점 투어",
  "Visit Namsan / N Seoul Tower": "남산 / N서울타워 가보기",
  "Walk through a hanok area": "한옥 거리 걷기",
  "Ride the subway with T-money": "티머니로 지하철 타기",
  "Use one Korean phrase in real life": "실제로 한국어 한 문장 써보기",
  "Open or prepare a local banking step": "한국 은행 관련 단계 시작하기",
  "Keep one important document in Landly": "중요 문서 하나를 Landly에 정리하기",
  "Tick this off after you try a proper local kimchi meal or side dish.": "제대로 된 김치 반찬이나 김치 요리를 먹어봤다면 체크해보세요.",
  "Complete one convenience store snack run after 10 PM.": "밤 10시 이후 편의점에서 간식 쇼핑을 해보세요.",
  "A classic first-time Korea landmark stamp.": "한국 첫 방문자에게 잘 어울리는 대표 랜드마크 스탬프예요.",
  "Explore a hanok village or a traditional alley.": "한옥마을이나 전통 골목을 걸어보세요.",
  "Use public transit on your own at least once.": "직접 대중교통을 한 번 이상 이용해보세요.",
  "Order food, ask for directions, or say thanks in Korean.": "음식 주문, 길 묻기, 감사 인사 중 하나를 한국어로 해보세요.",
  "For long-stay users: complete one banking or payment setup step.": "장기체류자라면 은행 또는 결제 관련 준비를 한 단계 진행해보세요.",
  "Upload or note down one stay-related document in your vault.": "스테이 관련 문서 하나를 문서함에 올리거나 기록해두세요.",
  "location": "장소",
  "culture": "문화",
  "life": "생활",

  // v07 Korean finish
  "Loading Calendar…": "캘린더를 불러오는 중…",
  "Preparing your saved route plans and events.": "저장된 경로 계획과 일정을 준비하고 있어요.",
  "First 90d": "정착 90일",
  "First 90 days": "정착 첫 90일",
  "International care": "국제 진료",
  "Tourist friendly": "관광객 이용 쉬움",
  "your arrival": "도착 일정",
  "Mom / Child / Friend 1": "엄마 / 아이 / 친구 1",
  "Stroller, cannot use stairs easily, needs pharmacy stop, etc.": "유모차 있음, 계단 이용이 어려움, 약국 경유 필요 등",
  "Night support": "야간 지원",
  "Item category": "품목 카테고리",
  "Refund Guide": "환급 가이드",
  "Immediate vs general refund": "즉시 환급 vs 일반 환급",
  "Immediate refund:": "즉시 환급:",
  "General refund:": "일반 환급:",
  "Some stores can process the refund at checkout when your purchase qualifies and your passport is available.": "조건에 맞는 구매이고 여권을 제시할 수 있으면 일부 매장에서 결제 시 바로 환급 처리가 가능해요.",
  "You may need to keep the receipt and complete refund-related steps later at an airport, kiosk, downtown counter, or other official channel.": "영수증을 보관한 뒤 공항, 키오스크, 시내 환급창구 등에서 나중에 환급 절차를 진행해야 할 수 있어요.",
  "Always confirm the latest store and airport process on the official channel because participation and procedures can change.": "참여 매장과 공항 절차는 바뀔 수 있으니 최신 공식 안내를 꼭 다시 확인하세요.",
  "Spanish": "스페인어",
  "French": "프랑스어",
  "zh": "중국어",
  "ja": "일본어",
  "Child": "아이",
  "Parent": "부모",
  "Friend": "친구",
  "Coworker": "동료",
  "Group member": "그룹 구성원",
  "No extra mobility support": "추가 이동 지원 없음",
  "Stroller": "유모차",
  "Wheelchair": "휠체어",
  "Slow walking": "보행이 느림",
  "Support center": "지원 센터",

  // Misc proper nouns / cities / labels
  "Jeju": "제주",
  "Gimpo Airport": "김포공항",
  "Gimhae Airport": "김해공항",
  "Jeju Airport": "제주공항",
  "Incheon International Airport": "인천국제공항",
  "Seoul central": "서울 중심부",
  "Busan station area": "부산역 일대",
  "Jeju city": "제주시",
  "Tourism": "관광",
  "Business": "비즈니스",
  "Study": "유학",
  "Long-term residence": "장기 체류",
  // v08 cleanup
  "Refund Checker": "환급 확인",
  "Sun": "일",
  "Mon": "월",
  "Tue": "화",
  "Wed": "수",
  "Thu": "목",
  "Fri": "금",
  "Sat": "토",
  "English": "영어",
  "Get urgent help now": "지금 바로 긴급 도움을 받으세요",
  "This situation may need emergency evaluation first. Use 119 or go to an emergency-ready hospital immediately.": "이 상황은 먼저 응급 평가가 필요할 수 있어요. 119에 연락하거나 응급 대응이 가능한 병원으로 바로 이동하세요.",
  "Breathing difficulty reported": "호흡 곤란이 보고되었어요",
  "Heavy bleeding reported": "심한 출혈이 보고되었어요",
  "Chest pain reported": "가슴 통증이 보고되었어요",
  "Severe intensity selected": "강한 통증 또는 심각도가 선택되었어요",
  "Look for counseling or support": "상담 또는 지원 기관을 먼저 확인하세요",
  "A counseling or mental-health support option may fit better than a general walk-in clinic.": "일반 의원보다 상담 또는 정신건강 지원이 더 적합할 수 있어요.",
  "Mental health support was selected": "정신건강 지원 항목이 선택되었어요",
  "A specialist visit may be the best fit": "전문 진료가 더 적합할 수 있어요",
  "Your situation looks better suited to a specialty clinic such as dermatology, dental care, or a checkup center.": "현재 상황은 피부과, 치과, 검진센터 같은 전문 진료가 더 적합해 보여요.",
  "A specialty category was selected": "전문 진료 카테고리가 선택되었어요",
  "Start with a pharmacy": "먼저 약국을 이용해보세요",
  "For mild issues at night, a pharmacy may be the quickest next step before deciding on a clinic visit.": "야간의 가벼운 증상은 병원 방문 전 약국이 가장 빠른 선택일 수 있어요.",
  "Night-time + mild symptoms": "야간 + 가벼운 증상",
  "Purchases under ₩15,000 are usually not eligible for tax refund.": "₩15,000 미만 구매는 일반적으로 세금 환급 대상이 아니에요.",
  "Used or opened products are generally not refundable for tax refund purposes.": "사용했거나 개봉한 상품은 일반적으로 세금 환급 대상이 아니에요.",
  "The product normally needs to leave Korea within 3 months of purchase.": "상품은 보통 구매 후 3개월 이내에 한국 밖으로 반출되어야 해요.",
  "Long-term residents are often outside the standard tourist tax refund scope.": "장기체류자는 일반적인 관광객 세금 환급 대상에서 제외되는 경우가 많아요.",
  "Some grocery or immediately consumed items can be restricted by store policy.": "식료품이나 즉시 소비한 품목은 매장 정책에 따라 제한될 수 있어요.",
  "This purchase looks broadly aligned with common tourist tax refund conditions.": "이 구매는 일반적인 관광객 세금 환급 조건에 대체로 부합해 보여요.",
  "30-day Korea setup review": "한국 정착 30일 점검",
  "Review telecom, banking, healthcare, and saved documents.": "통신, 은행, 건강관리, 저장 문서를 점검하세요.",
  "90-day Korea setup review": "한국 정착 90일 점검",
  "Double-check official registration, tax, labor, or school-related basics.": "등록, 세금, 노동, 학교 관련 기본 사항을 다시 확인하세요.",
  "Save receipts to review refund steps later": "나중에 환급 절차를 확인할 수 있도록 영수증을 저장하세요",
  "Landly Shop can keep your purchase notes together until your airport day.": "Landly Shop이 출국 전까지 구매 메모와 영수증을 함께 정리해드려요.",
  "Korea Immigration Service": "출입국·외국인청",
  "Call": "전화",
  "National Health Insurance Service": "국민건강보험공단",
  "National Institute for International Education": "국립국제교육원",
  "Seoul Metropolitan Government": "서울특별시",
  "Get official support when your travel plan changes or you need help.": "일정이 바뀌거나 도움이 필요할 때 공식 지원을 이용하세요.",
  "Fast and budget-friendly for central Seoul arrivals.": "서울 중심지 도착 시 빠르고 가성비가 좋아요.",
  "Best when you can handle one rail-based transfer without too much luggage.": "짐이 많지 않고 철도 환승 한 번 정도 괜찮다면 잘 맞아요.",
  "Balanced option when you want fewer transfers and direct neighborhood drop-offs.": "환승을 줄이고 동네 가까이 바로 가고 싶을 때 균형 잡힌 선택이에요.",
  "Most reliable choice for late arrivals or when transit options are limited.": "심야 도착이나 대중교통 선택지가 적을 때 가장 안정적이에요.",
  "Comfort-first option when you have luggage or want a simple door-to-door ride.": "짐이 많거나 문 앞까지 편하게 이동하고 싶을 때 좋아요.",
  "Mixed route combining rail and short taxi or bus transfer.": "철도와 짧은 택시·버스 이동을 조합한 경로예요.",
  "Strong fit for Seoul central hotels": "서울 중심 숙소에 특히 잘 맞아요",
  "Works well if you do not mind one transfer": "환승 한 번이 괜찮다면 잘 맞아요",
  "Good value if you will use transit often": "대중교통을 자주 탈 계획이면 가성비가 좋아요",

};

function interpolate(template: string, vars?: Record<string, string | number>) {
  if (!vars) return template;
  return template.replace(/\{(\w+)\}/g, (_, key) => String(vars[key] ?? `{${key}}`));
}

export function localizeText(language: Language, text?: string | null, vars?: Record<string, string | number>) {
  if (!text) return text ?? "";
  const base = language === "ko" ? koTextMap[text] ?? text : text;
  return interpolate(base, vars);
}

export function useLocalizedText() {
  const language = useAppStore((state) => state.user.language);
  return {
    language,
    isKo: language === "ko",
    lt: (text?: string | null, vars?: Record<string, string | number>) => localizeText(language, text, vars),
  };
}
